CREATE TABLE USUARIOWEB (
   ID SERIAL PRIMARY KEY,
   CODIGO VARCHAR(100) UNIQUE,
   NOME VARCHAR,
   SENHA VARCHAR,
   ultimoAcesso DATE default now()
);


INSERT INTO USUARIOWEB (CODIGO, NOME, SENHA) VALUES ('u0001', 'João Santos', '1111');
INSERT INTO USUARIOWEB (CODIGO, NOME, SENHA) VALUES ('u9999', 'Maria de Jesus', '9999');